[window]
decorations = "Buttonless"
padding = {x = 5}
dynamic_padding = true
startup_mode = "maximized"
opacity = 1

[font]
normal = { family = "0xProto Nerd Font" }
size = 20 

[terminal]
osc52 = "CopyPaste"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "F", mods = "Control|Shift", action = "ToggleSimpleFullscreen" },
]

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"
