[window]
decorations = "Buttonless"
padding = {x = 5}
dynamic_padding = true
startup_mode = "maximized"

[font]
normal = { family = "0xProto Nerd Font" }
size = 20 

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "F", mods = "Control|Shift", action = "ToggleSimpleFullscreen" },
]

