[window]
decorations = "Buttonless"
padding = {x = 5}
dynamic_padding = true
startup_mode = "maximized"
opacity = 1

[font]
normal = { family = "JetbrainsMono Nerd Font" }
size = 18 

[terminal]
osc52 = "CopyPaste"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewTab" },
  { key = "H", mods = "Control|Shift", action = "HideOtherApplications" },
  { key = "F", mods = "Control|Shift", action = "ToggleSimpleFullscreen" },
]
