# General Settings
fullscreen = false
vsync = true
cursor_animation_length = 0.13
cursor_trail_size = 0.8
cursor_antialiasing = true
cursor_vfx_mode = "railgun"
cursor_vfx_opacity = 200.0
cursor_vfx_particle_lifetime = 1.2
cursor_vfx_particle_density = 7.0
cursor_vfx_particle_speed = 10.0

# Font Settings
font = "FiraCode Nerd Font:h17"

# Transparency Settings
background_transparency = 0.8

# Window Settings
window_width = 1280
window_height = 720
window_maximized = false
window_title = "Neovide"

# Refresh Rate
refresh_rate = 60

# Clipboard Settings
use_primar_yclipboard = false

# Input Settings
input_use_logo = false
input_use_ctrl = true
input_use_alt = true
input_use_shift = true

# Performance Settings
frames_throttle_ms = 2

# Miscellaneous Settings
log_level = "info"
quit_on_focus_lost = false
